### ISSUE TITLE
Fails with contract packages that also include binary crates

### ISSUE THREAD

**Issue by uint** [mandrean/cw-optimizoor#23]
You can reproduce it by running `cw-optimizoor` against the head of [`cw-plus`](https://github.com/CosmWasm/cw-plus).

The solution is likely to make sure any invocation of `cargo build` includes the `--lib` parameter.

**Comment by mandrean** [comment]
Hey! Thanks for reporting.

Should already be fixed by https://github.com/mandrean/cw-optimizoor/pull/25 (released in `v0.9.0`), but also bumping `cw-plus` in the e2e suite to the latest version for good measure https://github.com/mandrean/cw-optimizoor/pull/28
