### ISSUE TITLE
Sometimes creates empty wasm binaries

### ISSUE THREAD

**Issue by de-husk** [mandrean/cw-optimizoor#3]
Awesome project! 

I ran into an issue trying to use it with this workspace: https://github.com/DA0-DA0/dao-contracts

It produced nearly empty optimized wasm binaries for `cw20_stake` and `cw_core` contracts. 

When I tried to use them, I got this error:
```
Error calling the VM: Error during static Wasm validation: Wasm contract doesn't have required export: "instantiate". Exports required by VM: ["allocate", "deallocate", "instantiate"].: create wasm contract failed: invalid request
```

Im wondering if `optimizoor` is compiling them with the library feature enabled?

**Comment by mandrean** [comment]
Hey @de-husk, thanks for reporting! Appreciate it. Will have a look.

**Comment by mandrean** [comment]
Okay, found the issue. Basically this can happen in monorepos where each member of the workspace has its own lockfile, like the `DA0-DA0` contracts

Current implementation assumes the monorepo shares one lockfile. Shouldn't be too difficult to support both cases

**Comment by mandrean** [comment]
I digged quite a bit deeper into this, and it seems like there is a bug/quirk in `cargo` itself:

If you have a workspace where a member (e.g. `DA0-DA0/cw_core`) is both a release binary in itself and a library dependency (with a feature flag set) to something else, then it will "simplify" the build process by only compiling that once with the feature flag set, causing that to spill over into the release binary as well!

![image](https://user-images.githubusercontent.com/4631744/180449470-1c9d61e3-5175-4c26-9b29-f0b509b621dd.png)

Looking into if there is a way to influence this.

**Comment by mandrean** [comment]
One can also argue that [DA0-DA0/dao-contracts ](https://github.com/DA0-DA0/dao-contracts) could be better at following clean software principles, like separation of concerns.

Ideally a contract (binary) shouldn't depend directly on another contract (binary) - any shared functionality should be in a separate package (library) under `packages/*`.

**Comment by mandrean** [comment]
Okay @de-husk, I have a workaround! Check https://github.com/mandrean/cw-optimizoor/pull/5

**Comment by de-husk** [comment]
This is looking good btw. Thanks for the quick fix!

**Comment by mandrean** [comment]
Thanks for reporting the bug! Much appreciated.
