### ISSUE TITLE
Unkown opcode error

### ISSUE THREAD

**Issue by Kayanski** [mandrean/cw-optimizoor#41]
With Rust 1.70, unsupported op codes appear when uploading the wasms on-chain. (See : https://github.com/CosmWasm/cosmwasm/issues/1727)

One fix is available on that issue. Would it be possible to implement that ?

Thanks

**Comment by gorgos** [comment]
Im on Rust 1.73 and CosmWasm 1.5 but don't see this any issues. I did however see this error with `cargo wasm`.

**Comment by Kayanski** [comment]
updating to cosmwasm-std 1.5 doesn't seem to solve the issue : 
`Error calling the VM: Error during static Wasm validation: Wasm bytecode could not be deserialized. Deserialization error: \"Unknown opcode 192\"`

**Comment by Kayanski** [comment]
Ok, this works with cosmwasm 1.5 indeed, thank you !
